//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HydraIRC.rc
//
#define IDCANCEL2                       3
#define IDC_FAVORITESADD_NEWFOLDER      3
#define ID_CHANNELLIST_JOIN             3
#define ID_CHANNELLIST_POPULATE         4
#define IDR_MAINFRAME                   200
#define ID_CHANNEL_PROPERTIES           201
#define ID_CHANNEL_SHOWSERVER           202
#define ID_CHANNEL_USERLIST             203
#define ID_CONNECT_SC_CONNECT           204
#define ID_CONNECT_SC_EDIT              205
#define ID_EDIT_CLEARBUFFER             206
#define ID_EDIT_COPYBUFFER              207
#define ID_FILE_CONNECT                 208
#define ID_FILE_DISCONNECT              209
#define ID_RECENTSERVERS_NONE           210
#define ID_TASKBARMENU_RESTORE          211
#define ID_VIEW_CHANNELMONITOR          214
#define ID_VIEW_GLOBALUSERLIST          215
#define ID_VIEW_IRCSERVERLIST           216
#define ID_VIEW_NOTICEQUEUE             217
#define ID_VIEW_OUTPUT                  218
#define ID_VIEW_PRIVMSGQUEUE            219
#define ID_VIEW_TRANSFERS               221
#define ID_WINDOW_MINIMIZEACTIVEWINDOW  222
#define ID_WINDOW_MINIMIZEALLWINDOWS    223
#define IDB_SERVERLIST                  224
#define IDB_TOOLBAR                     225
#define IDB_USERLIST                    226
#define IDC_EN_BROWSE                   227
#define IDD_ABOUTBOX                    228
#define IDD_CHANNELPROPERTIES           229
#define IDD_CONNECT                     230
#define IDD_EDITBUDDYGROUP              231
#define IDD_EDITNOTIFICATION            232
#define IDD_EDITSERVER                  233
#define IDD_PREFS                       234
#define IDD_PREFS_BUDDYGROUPS           235
#define IDD_PREFS_FILTERS               236
#define IDD_PREFS_IDENTITIES            237
#define IDD_PREFS_MISC                  238
#define IDD_PREFS_NOTIFICATIONS         239
#define IDD_PREFS_NOTIMPLEMENTED        240
#define IDD_PREFS_TEMPLATE              241
#define IDD_USERIDENTITY                242
#define IDI_CHANNEL                     243
#define IDD_PREFS_LOGGING               244
#define IDI_CHANNELMONITOR              245
#define IDD_PREFS_MESSAGES              246
#define IDD_PREFS_COMMANDPROFILES       247
#define IDI_MYINFORMATION               248
#define IDI_MYWARNING                   249
#define IDI_NOTE                        250
#define IDI_NOTICE                      251
#define IDI_OUTPUT                      252
#define IDI_PRIVMSG                     253
#define IDI_QUERY                       254
#define IDI_SERVER                      255
#define IDI_TRANSFERS                   256
#define IDI_USERLIST                    257
#define ID_CHANNEL_MONITOR              258
#define IDI_SERVERMONITOR               258
#define IDR_TASKBAR                     259
#define IDR_CONNECT_SERVERCONTEXT       260
#define ID_EDIT_REPEATFIND              261
#define IDR_CHANNELMONITOR_CONTEXT      263
#define IDC_CHANNELMONITOR_CLEARBUFFER  264
#define IDC_CHANNELMONITOR_COPYBUFFER   265
#define IDR_OUTPUT_CONTEXT              266
#define IDC_OUTPUT_CLEARBUFFER          267
#define IDC_OUTPUT_COPYBUFFER           268
#define IDR_CHANNEL_CONTEXT             269
#define IDC_CHILDFRAME_CLEARBUFFER      270
#define IDC_CHILDFRAME_COPYBUFFER       271
#define IDR_SERVER_CONTEXT              272
#define IDC_CHANNELMONITOR_STOPALLMONITORING 273
#define IDR_MENU1                       274
#define ID_HELP_HYDRAIRCONTHEWEB        289
#define IDD_FAVORITES                   291
#define ID_FAVORITES_ORGANIZEFAVORITES  292
#define IDD_FAVORITESADD                293
#define ID_FAVORITES_ADDTOFAVORITES     294
#define ID_Menu                         295
#define ID_VIEW_GUILAYOUT               296
#define ID_GUILAYOUT_HIDEALLDOCKERS     297
#define ID_GUILAYOUT_LAYOUT1            298
#define ID_GUILAYOUT_LAYOUT2            299
#define ID_GUILAYOUT_LAYOUT3            300
#define ID_GUILAYOUT_LAYOUT4            301
#define ID_GUILAYOUT_LAYOUT5            302
#define ID_VIEW_SERVERMONITOR           303
#define IDR_SERVERMONITOR_CONTEXT       304
#define IDC_SERVERMONITOR_CLEARBUFFER   305
#define IDC_SERVERMONITOR_COPYBUFFER    306
#define IDC_SERVERMONITOR_STOPALLMONITORING 307
#define ID_SERVER_MONITOR               308
#define IDD_PREFS_HIGHLIGHT             309
#define IDI_EVENTLOG                    312
#define IDB_BITMAP1                     313
#define IDB_TRANSFER                    313
#define IDD_ADDNETWORK                  314
#define IDR_QUERY_CONTEXT               315
#define IDR_MENU3                       316
#define IDR_DCCCHAT_CONTEXT             316
#define IDD_CHANNELLIST                 319
#define IDD_PREFS_NOTIMPLEMENTED1       320
#define IDD_PREFS_SELECTCHILD           320
#define ID_EBG_OK                       1000
#define ID_EN_OK                        1001
#define ID_ESRV_OK                      1002
#define ID_UI_OK                        1003
#define IDC_ABOUT_VERSIONINFO           1004
#define IDC_BUDDYGROUPS_ADD             1005
#define IDC_BUDDYGROUPS_BUDDYLIST       1006
#define IDC_BUDDYGROUPS_DELETE          1007
#define IDC_BUDDYGROUPS_EDIT            1008
#define IDC_BUDDYGROUPS_GROUP           1009
#define IDC_BUDDYGROUPS_HOST            1010
#define IDC_BUDDYGROUPS_NICK            1011
#define IDC_BUDDYGROUPS_NICKADD         1012
#define IDC_BUDDYGROUPS_NICKDELETE      1013
#define IDC_CHANNELPROPERTIES_INVITE    1014
#define IDC_CHANNELPROPERTIES_KEY       1015
#define IDC_CHANNELPROPERTIES_KEYSTRING 1016
#define IDC_CHANNELPROPERTIES_LIMIT     1017
#define IDC_CHANNELPROPERTIES_LIMITSTRING 1018
#define IDC_CHANNELPROPERTIES_SETTINGSFRAME 1019
#define IDC_CHANNELPROPERTIES_TOPIC     1020
#define IDC_CONNECT_EDITIDENTITY        1021
#define IDC_CONNECT_IDENTITY            1022
#define IDC_CONNECT_IDENTITYFRAME       1023
#define IDC_CONNECT_SERVERFRAME         1024
#define IDC_CONNECT_URILABEL            1025
#define IDC_EBG_NAME                    1027
#define IDC_EBG_NETWORK                 1028
#define IDC_EN_ENABLED                  1029
#define IDC_EN_EVENT                    1030
#define IDC_EN_FILENAME                 1031
#define IDC_EN_FLASHTASKBAR             1032
#define IDC_EN_HASSOUND                 1033
#define IDC_EN_SELECTSYSTEMSOUND        1034
#define IDC_EN_SOUNDFILE                1035
#define IDC_EN_SYSTEMSOUND              1036
#define IDC_EN_MATCHSTRING              1037
#define IDC_EN_FOREGROUNDCOLOR          1038
#define IDC_EN_BACKGROUNDCOLOR          1039
#define IDC_EN_HIGHLIGHTWHOLELINE       1040
#define IDC_EN_HIGHLIGHTCASESENSITIVE   1041
#define IDC_FILTERS_ADD                 1042
#define IDC_FILTERS_EXCLUDE             1043
#define IDC_FILTERS_INCLUDE             1044
#define IDC_FILTERS_OBJECT              1045
#define IDC_FILTERS_REMOVE              1046
#define IDC_FILTERS_DELETE              1046
#define IDC_FILTERS_UNUSED              1047
#define IDC_FILTERS_UNUSEDTEXT          1048
#define IDC_FILTERS_USED                1049
#define IDC_FILTERS_USEDTEXT            1050
#define IDC_IDENTITIES_LIST             1051
#define IDC_IDENTITY_DELETE             1052
#define IDC_IDENTITY_EDIT               1053
#define IDC_IDENTITY_NEW                1054
#define IDC_MISC_PROPERTYLIST           1055
#define IDC_NOTIFICATIONS_DELETE        1056
#define IDC_NOTIFICATIONS_EDIT          1057
#define IDC_NOTIFICATIONS_EVENTS        1058
#define IDC_NOTIFICATIONS_GROUP         1059
#define IDC_NOTIFICATIONS_NEW           1060
#define IDC_PREFS_PLACEHOLDER           1061
#define IDC_PREFSTREE                   1062
#define IDC_SERVERTREE                  1063
#define IDC_SERVERURI                   1064
#define IDC_STATIC_CONFIGURE            1065
#define IDC_STATIC_INFO                 1066
#define IDC_STATIC_OPTION               1067
#define IDC_UI_ADD                      1068
#define IDC_UI_DELETE                   1069
#define IDC_UI_DESCRIPTION              1070
#define IDC_UI_DOWN                     1071
#define IDC_UI_IDENTDOS                 1072
#define IDC_UI_IDENTDUSERNAME           1073
#define IDC_UI_NICK                     1074
#define IDC_UI_NICKLIST                 1075
#define IDC_UI_REALNAME                 1076
#define IDC_UI_UP                       1077
#define IDC_UI_USERNAME                 1078
#define IDC_LOGGING_LOGROOTFOLDER       1079
#define IDC_LOGGING_SERVERLOGFORMAT     1080
#define IDC_LOGGING_LOGSERVER           1081
#define IDC_LOGGING_CHANNELLOGFORMAT    1082
#define IDC_LOGGING_LOGCHANNEL          1083
#define IDC_LOGGING_CREATENETWORKFOLDER 1084
#define IDC_LOGGING_QUERYLOGFORMAT      1085
#define IDC_MESSAGES_CHANNELMEMBERNOTICESONLY 1085
#define IDC_LOGGING_LOGQUERY            1086
#define IDC_MESSAGES_CROSSNETWORKNOTICEFORWARDING 1086
#define IDC_LOGGING_ENABLE              1087
#define IDC_MESSAGES_FORWARDNOTICES     1087
#define IDC_LOGGING_DCCCHATLOGFORMAT    1088
#define IDC_MESSAGES_FORWARDMESSAGES    1088
#define IDC_LOGGING_LOGDCCCHAT          1089
#define IDC_MESSAGES_CREATEQUERYWINDOWSAUTOMATICALLY 1089
#define IDC_MESSAGES_CREATEQUERYWINDOWSHIDDEN 1090
#define IDC_LOGGING_DCCCHATSTRIPCODES   1090
#define IDC_MESSAGES_RESTRICTMESSAGES   1091
#define IDC_LOGGING_QUERYSTRIPCODES     1091
#define IDC_MESSAGES_RESTRICTNOTICES    1092
#define IDC_LOGGING_CHANNELSTRIPCODES   1092
#define IDC_MESSAGES_QUERYNOTIFYREACTIVATEDELAY 1093
#define IDC_LOGGING_SERVERSTRIPCODES    1093
#define IDC_MESSAGES_MAXNOTICELOGITEMS  1094
#define IDC_LOGGING_LOGVIEWER           1094
#define IDC_MESSAGES_MAXPRIVMSGLOGITEMS 1095
#define IDC_MESSAGES_MAXNOTICELOGAGEMINS 1096
#define IDC_MESSAGES_MAXPRIVMSGLOGAGEMINS 1097
#define IDC_COMMANDPROFILES_PROFILES    1097
#define IDC_MESSAGES_REMOVEPRIVMSGITEMS 1098
#define IDC_COMMANDPROFILES_COMMANDS    1098
#define IDC_MESSAGES_REMOVENOTICEITEMS  1099
#define IDC_COMMANDPROFILES_ADD         1099
#define IDC_COMMANDPROFILES_DELETE      1100
#define IDC_COMMANDPROFILES_RENAME      1101
#define IDC_COMMANDPROFILES_COPY        1102
#define IDC_COMMANDPROFILES_NAME        1103
#define IDC_CONNECT_PASSWORD            1104
#define IDC_CONNECT_PASSWORDLABEL       1105
#define IDC_FAVORITES_TREE              1106
#define IDC_FAVORITES_DELETE            1108
#define IDC_FAVORITES_NEWFOLDER         1109
#define IDC_FAVORITES_NOTE              1110
#define IDC_FAVORITESADD_NAME           1111
#define IDC_FAVORITESADD_TREE           1112
#define IDC_IDENTITY_DEFAULT            1115
#define IDC_IDENTITY_SETDEFAULT         1116
#define IDC_IDENTITY_NOTE               1117
#define IDC_HIGHLIGHT_NEW               1118
#define IDC_HIGHLIGHT_EDIT              1119
#define IDC_HIGHLIGHT_DELETE            1120
#define IDC_HIGHLIGHT_LIST              1121
#define IDC_EN_PICKFGCOLOR              1123
#define IDC_EN_PICKBGCOLOR              1124
#define IDC_EN_LOGINEVENTLOG            1125
#define IDC_EN_AUDIBLERECTANGLE         1126
#define IDC_EN_VISUALRECTANGLE          1127
#define IDC_ESRV_ADDRESS                1128
#define IDC_ESRV_PORT                   1129
#define IDC_ESRV_DESCRIPTION            1130
#define IDC_ESRV_NETWORK                1131
#define IDC_ESRV_PRIORITY               1132
#define IDC_CONNECT_ADDNETWORK          1134
#define IDC_CONNECT_ADDSERVER           1135
#define IDC_ESRV_PASSWORD               1136
#define IDC_ESRV_PASSWORD2              1137
#define IDC_ANET_NAME                   1137
#define ID_ANET_OK                      1138
#define IDC_LOGGING_LOGVIEWERBROWSE     1139
#define IDC_CONNECT_NOTELABEL           1140
#define IDC_URLCATCHER_FIND             1142
#define ID_CHANNELLIST_SHOWFAVORITES    1142
#define IDC_URLCATCHER_VIEWTYPE         1143
#define ID_CHANNELLIST_SHOWALL          1143
#define IDC_TREE1                       1144
#define ID_CHANNELLIST_SEARCHTEXT       1146
#define ID_CHANNELLIST_SEARCHSELECT     1147
#define ID_CHANNELLIST_LIST             1148
#define ID_CHANNELLIST_USERSMIN         1149
#define ID_CHANNELLIST_USERSMAX         1150
#define ID_CHANNELLIST_PROGRESS         1151
#define IDC_ANET_IDENTITYLIST           1152
#define ID_CHANNELLIST_SELECTGROUP      1153
#define IDC_BUDDYGROUPS_GROUPSTATIC     1154
#define IDC_BUDDYGROUPS_MEMBERSSTATIC   1155
#define IDC_CHILDFRAME_VERBOSELEVEL_LEVEL0 1156
#define IDC_CHILDFRAME_VERBOSELEVEL_LEVEL1 1157
#define IDC_CHILDFRAME_VERBOSELEVEL_LEVEL2 1158
#define IDC_CHILDFRAME_VERBOSELEVEL_LEVEL3 1159
#define IDR_USERLIST_CONTEXT            4000
#define ID_CONTEXT_CLIPBOARD            4001
#define ID_USERLISTFIRST                4002
#define ID_USERLIST_CB_COPYUSERNAME     4002
#define ID_USERLIST_CB_COPYHOSTMASK     4003
#define ID_USERLIST_QUERY               4004
#define ID_USERLIST_DCCSENDFILE         4005
#define ID_USERLIST_DCCCHAT             4006
#define ID_USERLIST_OP                  4007
#define ID_USERLIST_DEOP                4008
#define ID_USERLIST_VOICE               4009
#define ID_USERLIST_DEVOICE             4010
#define ID_USERLIST_WHOIS               4011
#define ID_USERLIST_SLAP                4012
#define ID_USERLIST_KICK                4013
#define ID_USERLIST_BAN                 4014
#define ID_USERLIST_KICKANDBAN          4015
#define ID_USERLIST_SHOWBUDDYGROUPS     4016
#define ID_USERLIST_CTCP_VERSION        4017
#define ID_USERLIST_CTCP_CLIENT         4018
#define ID_USERLIST_CTCP_USER           4019
#define ID_USERLIST_CTCP_PING           4020
#define ID_USERLIST_CTCP_TIME           4021
#define ID_USERLIST_ADMIN               4022
#define ID_USERLIST_DEADMIN             4023
#define ID_USERLIST_HALFOP              4024
#define ID_USERLIST_DEHALFOP            4025
#define ID_USERLISTLAST                 4025
#define ID_HELP_DOCUMENTATION           32786
#define ID_HELP_REPORTABUG              32787
#define ID_HELP_FORUMS                  32788
#define ID_VIEW_EVENTLOG                32789
#define ID_CONTEXT_VERBOSELEVEL         32790
#define ID_CONNECT_SC_DELETE            32805
#define IDC_CHILDFRAME_VIEWLOGFILE      32809
#define ID_OPTIONS_LOGGING              32815
#define ID_OPTIONS_TIMESTAMPS           32816
#define ID_OPTIONS_AUDIOMUTE            32817
#define ID_OPTIONS_PREFS                32818
#define ID_HELP_RECENTCHANGES           32819
#define ID_HELP_ONLINEDOCUMENTATION     32820
#define ID_CONTEXT_CYCLE                32827
#define IDC_CHILDFRAME_CYCLE            32828
#define ID_OPTIONS_TOGGLEUSERLIST       32830
#define ID_OPTIONS_TOGGLEINFO           32831
#define ID_OPTIONS_TOGGLEHEADER         32832
#define IDC_CHILDFRAME_DCCSEND          32833
#define IDC_CHILDFRAME_DCCCHAT          32834
#define IDC_CHILDFRAME_WHOIS            32835
#define IDC_CHILDFRAME_ADD              32836
#define ID_HELP_DONATE                  32841
#define ID_VIEW_URLCATCHER              32842
#define ID_DCCRECEIVE_CANCEL            32843
#define ID_DCCRECEIVE_REMOVEFROMLIST    32844
#define ID_DCCSEND_CANCEL               32848
#define ID_DCCSEND_REMOVEFROMLIST       32849
#define ID_DCCSEND_RETRY                32850
#define ID_CONNECT_SC_ADD               32855
#define ID_CONNECT_NC_ADD               32856
#define ID_CONNECT_NC_EDIT              32857
#define ID_CONNECT_NC_DELETE            32858
#define ID_CONNECT_NC_ADDSERVER         32860
#define ID_CHANNEL_CHANNELLIST          32861
#define ID_CONTEXT_CTCP                 32865
#define ID_CTCP_VERSION                 32866
#define ID_CTCP_CLIENT                  32867
#define ID_CTCP_USERINFO                32868
#define ID_CTCP_PING                    32869
#define ID_CONTEXT_SLAP                 32870
#define ID_Menu32871                    32871
#define ID_CTCP_TIME                    32872
#define ID_USERLIST_CONTEXT_SLAP        32873
#define ID_VIEW_CHANNELLIST             32874
#define ID_FAVORITES_ADDTOFAVORITES32876 32876
#define ID_FAVORITES_ORGANIZEFAVORITES32877 32877
#define ID_CHANNEL_MONITOR32878         32878
#define ID_CHANNEL_SHOWSERVER32879      32879
#define ID_CHANNEL_PROPERTIES32880      32880
#define ID_CHANNEL_CHANNELLIST32881     32881
#define ID_CONTEXT_QUERY                32882
#define ID_OPERATOR_ADMIN               32883
#define ID_OPERATOR_DEADMIN             32884
#define ID_OPERATOR_HALFOP              32885
#define ID_OPERATOR_DEHALFOP            32886

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         32891
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
